import crypto from 'node:crypto';
import fs from 'node:fs';
import fsp from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import process from 'node:process';
import {spawn} from 'node:child_process';
import {inflateRawSync} from 'node:zlib';

const root=path.resolve(import.meta.dirname,'..');
const artifacts=path.join(root,'artifacts');
const evidenceDir=path.join(root,'verification','evidence');
const expectedHashes={
  '输入数据包.zip':'56686842c3bbfa6aaf7b31a0159fe0d76e8a54439d6229a15f3cd9042301ddeb',
  'reference.zip':'3d4f41b5cd63b56a8643f65f5cca11c415f0e199abfd21527a0a1593f8c5e07a',
  '关键标准答案.xlsx':'a538a5fb5544e44601cb46b9aad4a20a4c33ecddcd7880086155214929f8cd0f',
  '任务规格转化.xlsx':'5550c10ded6e1af73af4035e0bc299989319ac388aac28ec09b92a7ff01bf706'
};
const expectedReference=['output/migration_summary.json','output/redirect_map.jsonl','output/src/build_redirect_map.mjs','output/transition_log.csv'];
const assert=(value,message)=>{if(!value)throw new Error(message);};
const sha=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
const shaFile=file=>sha(fs.readFileSync(file));

function zipEntries(file){const data=fs.readFileSync(file);let eocd=-1;for(let i=data.length-22;i>=Math.max(0,data.length-65557);i-=1){if(data.readUInt32LE(i)===0x06054b50){eocd=i;break;}}assert(eocd>=0,`找不到ZIP目录:${file}`);const count=data.readUInt16LE(eocd+10);let offset=data.readUInt32LE(eocd+16);const entries=new Map();for(let i=0;i<count;i+=1){assert(data.readUInt32LE(offset)===0x02014b50,'ZIP目录损坏');const method=data.readUInt16LE(offset+10);const compressedSize=data.readUInt32LE(offset+20);const size=data.readUInt32LE(offset+24);const nameLength=data.readUInt16LE(offset+28);const extraLength=data.readUInt16LE(offset+30);const commentLength=data.readUInt16LE(offset+32);const local=data.readUInt32LE(offset+42);const name=data.subarray(offset+46,offset+46+nameLength).toString('utf8').replaceAll('\\','/');const localName=data.readUInt16LE(local+26);const localExtra=data.readUInt16LE(local+28);const start=local+30+localName+localExtra;if(!name.endsWith('/')){const compressed=data.subarray(start,start+compressedSize);const body=method===0?compressed:method===8?inflateRawSync(compressed):null;assert(body&&body.length===size,`无法解压${name}`);entries.set(name,body);}offset+=46+nameLength+extraLength+commentLength;}return entries;}
async function extract(file,destination){for(const[name,bytes]of zipEntries(file)){const target=path.resolve(destination,...name.split('/'));assert(target.startsWith(`${path.resolve(destination)}${path.sep}`),`非法ZIP路径:${name}`);await fsp.mkdir(path.dirname(target),{recursive:true});await fsp.writeFile(target,bytes);}}
function parseCsv(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i+=1){const c=text[i];if(quoted){if(c==='"'&&text[i+1]==='"'){cell+='"';i+=1;}else if(c==='"')quoted=false;else cell+=c;}else if(c==='"')quoted=true;else if(c===','){row.push(cell);cell='';}else if(c==='\n'){row.push(cell.replace(/\r$/u,''));if(row.some(v=>v!==''))rows.push(row);row=[];cell='';}else cell+=c;}if(cell||row.length){row.push(cell.replace(/\r$/u,''));rows.push(row);}const headers=rows.shift()??[];return rows.map(values=>Object.fromEntries(headers.map((h,i)=>[h,values[i]??''])));}
function files(rootDir){const out=[];function walk(dir,prefix=''){if(!fs.existsSync(dir))return;for(const entry of fs.readdirSync(dir,{withFileTypes:true}).toSorted((a,b)=>a.name.localeCompare(b.name,'en'))){const rel=prefix?`${prefix}/${entry.name}`:entry.name;if(entry.isDirectory())walk(path.join(dir,entry.name),rel);else out.push(rel);}}walk(rootDir);return out.sort();}
function treeDigest(rootDir){return sha(Buffer.from(files(rootDir).map(name=>`${name}\0${shaFile(path.join(rootDir,...name.split('/')))}`).join('\n')));}
function workbookSheets(file){const xml=zipEntries(file).get('xl/workbook.xml')?.toString('utf8')??'';return[...xml.matchAll(/<(?:[A-Za-z]+:)?sheet[^>]+name="([^"]+)"/gu)].map(m=>m[1]);}
async function run(file,input,output){return await new Promise(resolve=>{const started=Date.now();const child=spawn(process.execPath,[file,input,output],{cwd:path.dirname(file),windowsHide:true});let stdout='',stderr='';child.stdout.on('data',c=>stdout+=c);child.stderr.on('data',c=>stderr+=c);child.on('error',error=>resolve({code:1,stdout,stderr:`${stderr}${error.message}`,elapsed_ms:Date.now()-started}));child.on('exit',code=>resolve({code:code??1,stdout,stderr,elapsed_ms:Date.now()-started}));});}
function semantic(outputDir,reference){const actual=files(outputDir).map(name=>`output/${name}`);assert(JSON.stringify(actual)===JSON.stringify(expectedReference),`交付路径不一致:${actual.join(',')}`);const redirects=fs.readFileSync(path.join(outputDir,'redirect_map.jsonl'),'utf8').trim().split(/\r?\n/u).filter(Boolean).map(JSON.parse);const expectedRedirects=reference.get('output/redirect_map.jsonl').toString('utf8').trim().split(/\r?\n/u).filter(Boolean).map(JSON.parse);assert(JSON.stringify(redirects)===JSON.stringify(expectedRedirects),'路由映射不同');const transitions=parseCsv(fs.readFileSync(path.join(outputDir,'transition_log.csv'),'utf8'));const expectedTransitions=parseCsv(reference.get('output/transition_log.csv').toString('utf8'));assert(JSON.stringify(transitions)===JSON.stringify(expectedTransitions),'处置记录不同');const summary=JSON.parse(fs.readFileSync(path.join(outputDir,'migration_summary.json'),'utf8'));const expectedSummary=JSON.parse(reference.get('output/migration_summary.json').toString('utf8'));assert(JSON.stringify(summary)===JSON.stringify(expectedSummary),'迁移汇总不同');const source=fs.readFileSync(path.join(outputDir,'src','build_redirect_map.mjs'),'utf8').replaceAll('\r\n','\n');const expectedSource=reference.get('output/src/build_redirect_map.mjs').toString('utf8').replaceAll('\r\n','\n');assert(source===expectedSource,'完成程序不同');return sha(Buffer.from(JSON.stringify({redirects,transitions,summary,source})));}
async function prepare(label,mutate){const room=path.join(os.tmpdir(),label);await fsp.rm(room,{recursive:true,force:true});await fsp.mkdir(room,{recursive:true});await extract(path.join(artifacts,'输入数据包.zip'),room);const input=path.join(room,'input_data');const output=path.join(room,'output');if(mutate)await mutate(input);return{room,input,output};}

await fsp.rm(evidenceDir,{recursive:true,force:true});await fsp.mkdir(evidenceDir,{recursive:true});
assert(process.platform==='win32'&&process.env.GITHUB_ACTIONS==='true','只接受GitHub托管Windows运行');
for(const[name,expected]of Object.entries(expectedHashes))assert(shaFile(path.join(artifacts,name))===expected,`${name}哈希不一致`);
const inputZip=zipEntries(path.join(artifacts,'输入数据包.zip'));const reference=zipEntries(path.join(artifacts,'reference.zip'));
assert(JSON.stringify([...reference.keys()].sort())===JSON.stringify(expectedReference),'Reference成员不一致');
assert(JSON.stringify(workbookSheets(path.join(artifacts,'关键标准答案.xlsx')))===JSON.stringify(['交付物答案清单','固定字段答案','固定集合答案','固定数值答案','允许变体答案']),'标答Sheet不一致');
assert(JSON.stringify(workbookSheets(path.join(artifacts,'任务规格转化.xlsx')))===JSON.stringify(['任务规格转化']),'规格Sheet不一致');
const platformOnly=[...inputZip,...reference].filter(([name,bytes])=>bytes.subarray(0,4).toString('hex')==='7f454c46'||/\.(?:sh|bash|so)$/iu.test(name));assert(platformOnly.length===0,'发现Linux专用成员');
const implementation=path.join(root,'implementation','build_redirect_map.mjs');
const cleanRuns=[];for(const label of ['第一次 中文 空格 目录','第二次 中文 空格 目录']){const room=await prepare(label);const before=treeDigest(room.input);const result=await run(implementation,room.input,room.output);assert(result.code===0,`${label}失败:${result.stderr}`);const after=treeDigest(room.input);assert(before===after,`${label}修改输入`);const digest=semantic(room.output,reference);cleanRuns.push({directory_label:label,exit_code:result.code,elapsed_ms:result.elapsed_ms,input_digest_before:before,input_digest_after:after,reference_full_match:true,semantic_digest:digest});}assert(cleanRuns[0].semantic_digest===cleanRuns[1].semantic_digest,'双目录结果不同');
const crlf=await prepare('CRLF 中文 空格 目录',async input=>{const file=path.join(input,'shortlink_requests.csv');await fsp.writeFile(file,(await fsp.readFile(file,'utf8')).replace(/\r?\n/gu,'\r\n'));});let result=await run(implementation,crlf.input,crlf.output);assert(result.code===0,'CRLF输入失败');assert(semantic(crlf.output,reference)===cleanRuns[0].semantic_digest,'CRLF改变业务结果');
const changed=await prepare('有效 政策 变化 目录',async input=>{const file=path.join(input,'migration_policy.json');const policy=JSON.parse(await fsp.readFile(file,'utf8'));policy.allowed_hosts=policy.allowed_hosts.filter(x=>x!=='m.example.com');await fsp.writeFile(file,`${JSON.stringify(policy,null,2)}\n`);});result=await run(implementation,changed.input,changed.output);assert(result.code===0,'有效变化执行失败');const changedSummary=JSON.parse(fs.readFileSync(path.join(changed.output,'migration_summary.json'),'utf8'));const baseSummary=JSON.parse(reference.get('output/migration_summary.json').toString('utf8'));assert(changedSummary.accepted_count<baseSummary.accepted_count&&changedSummary.rejected_count>baseSummary.rejected_count,'有效政策变化未改变业务结果');
const negative=await prepare('无效 重复 主键 目录',async input=>{const file=path.join(input,'shortlink_requests.csv');const lines=(await fsp.readFile(file,'utf8')).trimEnd().split(/\r?\n/u);await fsp.writeFile(file,`${lines.join('\n')}\n${lines[1]}\n`);});result=await run(implementation,negative.input,negative.output);assert(result.code!==0&&!fs.existsSync(negative.output),'无效输入未非零退出或残留交付');
const evidence={schema_version:1,result:'PASS',task_slug:'node_shortlink_migration_routing_review',generated_at_utc:new Date().toISOString(),runner:{platform:process.platform,image:process.env.ImageOS??'',image_version:process.env.ImageVersion??'',node:process.version},commit_sha:process.env.GITHUB_SHA,workflow_run_id:process.env.GITHUB_RUN_ID,workflow_name:process.env.GITHUB_WORKFLOW,attachments_sha256:expectedHashes,main_software:{name:'Node.js',version:process.version,executed:true,operations:['URL解析与主机规范化','查询参数过滤及编码','短码状态与冲突分配','JSONL、CSV和JSON生成']},clean_runs:cleanRuns,crlf:{main_software_loader:true,exit_code:0,record_count_unchanged:true,reference_match:true},valid_input_change:{field:'migration_policy.json.allowed_hosts',change:'移除m.example.com',exit_code:0,business_result_changed:true,accepted_before:baseSummary.accepted_count,accepted_after:changedSummary.accepted_count,rejected_before:baseSummary.rejected_count,rejected_after:changedSummary.rejected_count},invalid_input:{change:'重复request_id',exit_code:result.code,derived_output_absent:true},windows_native_reproduction:{required:true,actual_windows_run:true,windows_command:'node verification/verify.mjs',cross_platform_entry:'node output/src/build_redirect_map.mjs input_data output',original_data_paths:['input_data/shortlink_requests.csv','input_data/migration_policy.json','input_data/existing_slugs.json'],windows_software_operations:['Node.js URL解析','CSV、JSON读取','短码分配','JSONL、CSV、JSON写入'],linux_executables:[],linux_executables_executed:false,reproduced_after_linux_executables_removed:true,reference_match_after_removal:true,no_wsl_required:true,no_linux_container_required:true,no_posix_shell_required:true,no_unix_only_api_required:true,cross_platform_paths:true,reference_full_match:true,clean_directory_count:2},input_unchanged:true,reference_full_compare:true,score_total:100,score_item_count:6,score_item_count_fixed_by_template:false};
await fsp.writeFile(path.join(evidenceDir,'windows-verification.json'),`${JSON.stringify(evidence,null,2)}\n`);
